{{- if and .Values.querier.enabled .Values.querier.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sigil.fullname" . }}-querier
  labels:
    {{- include "sigil.labels" . | nindent 4 }}
    app.kubernetes.io/component: querier
  {{- with .Values.querier.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.querier.service.type }}
  ports:
    - name: http
      port: {{ .Values.querier.service.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "sigil.querierSelectorLabels" . | nindent 4 }}
{{- end }}
