FROM node:24-bookworm@sha256:00e9195ebd49985a6da8921f419978d85dfe354589755192dc090425ce4da2f7

ENV GOPATH /opt/go
ENV PATH $PATH:$GOPATH/bin:/usr/local/go/bin
ENV GOCACHE /opt/go-cache/build
ENV GOMODCACHE /opt/go-cache/mod
ENV GOFLAGS="-buildvcs=false"

COPY --from=golang:1.26-bookworm@sha256:2a0ba12e116687098780d3ce700f9ce3cb340783779646aafbabed748fa6677c /usr/local/go/ /usr/local/go/
RUN /usr/local/go/bin/go install github.com/magefile/mage@v1.15.0

COPY package.json /tmp/package.json
RUN corepack enable && cd /tmp && corepack install
RUN pnpm config set store-dir /opt/pnpm-store

EXPOSE 35728
EXPOSE 35729
