FROM golang:1.26-bookworm@sha256:2a0ba12e116687098780d3ce700f9ce3cb340783779646aafbabed748fa6677c

WORKDIR /app/sigil

ENV GOCACHE /opt/go-cache/build
ENV GOMODCACHE /opt/go-cache/mod

RUN go install github.com/air-verse/air@v1.62.0

CMD ["air", "-c", ".air.toml"]
