FROM golang:1.26-bookworm@sha256:8e8aa801e8417ef0b5c42b504dd34db3db911bb73dba933bd8bde75ed815fdbb

WORKDIR /app/sigil

ENV GOCACHE /opt/go-cache/build
ENV GOMODCACHE /opt/go-cache/mod

RUN go install github.com/air-verse/air@v1.62.0

EXPOSE 8080 4317

CMD ["air", "-c", ".air.toml"]
