FROM node:24-bookworm@sha256:5a593d74b632d1c6f816457477b6819760e13624455d587eef0fa418c8d0777b

ENV GOPATH /opt/go
ENV PATH $PATH:$GOPATH/bin:/usr/local/go/bin
ENV GOCACHE /opt/go-cache/build
ENV GOMODCACHE /opt/go-cache/mod
ENV GOFLAGS="-buildvcs=false"

COPY --from=golang:1.26-bookworm@sha256:8e8aa801e8417ef0b5c42b504dd34db3db911bb73dba933bd8bde75ed815fdbb /usr/local/go/ /usr/local/go/
RUN /usr/local/go/bin/go install github.com/magefile/mage@v1.15.0

COPY package.json /tmp/package.json
RUN corepack enable && cd /tmp && corepack install
RUN pnpm config set store-dir /opt/pnpm-store

EXPOSE 35728
EXPOSE 35729
