FROM golang:1.26-bookworm@sha256:eae3cdfa040d0786510a5959d36a836978724d03b34a166ba2e0e198baac9196

WORKDIR /app/sigil

ENV GOCACHE /opt/go-cache/build
ENV GOMODCACHE /opt/go-cache/mod

RUN go install github.com/air-verse/air@v1.62.0

CMD ["air", "-c", ".air.toml"]
